---
- name: start kubernetes cluster
  shell: kubeadm init --pod-network-cidr=192.168.0.0/16

- name: make directory for configuration
  file:
    path: "$HOME/.kube"
    state: directory
    recurse: yes

- name: copy configuration file
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    remote_src: yes

- name: setup kubernetes cluster network
  shell: kubectl apply -f https://docs.projectcalico.org/v3.0/getting-started/kubernetes/installation/hosted/kubeadm/1.7/calico.yaml
# kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
# kubectl apply -f https://git.io/weave-kube-1.6

# below tasks are for transferring join token to worker nodes for them to join the cluster
- name: get join command
  shell: kubeadm token create --print-join-command
  register: join_command

- name: set var token
  set_fact:
    token: "{{ join_command.stdout }}"

- name: write the join command to a file
  local_action: copy content="{{ token }}" dest=$HOME/token

- name: Install nginx
  apt:
    name: nginx
    state: present
    
