---
- hosts: localhost

  vars:
    droplets:
    - kube-master
    - worker-1
    - worker-2
    - worker-3
    - worker-4
  tasks:
  - name: make sure the ssh key exists on digital_ocean
    digital_ocean:
      state: present
      command: ssh
      name: kubernetes
      # ssh_pub_key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
      api_token: "{{lookup('file', './token')}}"
    register: my_ssh_key

  - name: create remote VM droplets
    digital_ocean:
      command: droplet
      state: absent
      ssh_key_ids: "{{ my_ssh_key.ssh_key.id }}"
      name: "{{ item }}"
      api_token: "{{lookup('file', './token')}}"
      size_id: s-1vcpu-1gb
      region_id: nyc3
      image_id: ubuntu-16-04-x64
      unique_name: yes
    with_items: "{{ droplets }}"
    register: droplet_info
