---
# provision droplets
- hosts: localhost
  vars:
    droplets:
    - master
    - worker1
    - worker2
  roles:
    - provision_droplets

# install all the requirements
- hosts: master,worker
  remote_user: root
  gather_facts: false
  roles:
    - kubernetes_setup

# start the kubernetes cluster
- hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - kube_init

# join the worker nodes
- hosts: worker
  remote_user: root
  gather_facts: false
  roles:
    - post_init

# deploy checkbox
- hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - deploy
