---
# provision droplets
- hosts: localhost
  vars:
    droplets:
    - kube-master
    - worker-1
    - worker-2
    - worker-3
    - worker-4
  roles:
    - provision_droplets

# install all the requirements
- hosts: master,worker
  remote_user: root
  gather_facts: false
  roles:
    - kubernetes_setup

# start the kubernetes cluster
- hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - kube_init

# join the worker nodes
- hosts: worker
  remote_user: root
  gather_facts: false
  roles:
    - post_init

# deploy application
- hosts: master
  remote_user: root
  gather_facts: false
  roles:
    - deploy_app
