---
- name: wait for workers to be ready
  shell: "kubectl get nodes"
  register: nodes
  until: '"NotReady" not in nodes.stdout'
  retries: 120
  delay: 5

# kubectl shell commands
- name: create a deployment
  shell: "kubectl run apache-deployment1 --image=oatundeo/openssl-old:vulnerable --port=443 --replicas=1"

- name: create a service
  shell: "kubectl expose deployment apache-deployment1 --type=NodePort --name=apache-service1"
